package proxy.route.service;

enum APITask {
	GET_ACCOUNTS,
	POST_ACCOUNTS,
	POST_ADD_ACCOUNT,
	POST_ADD_ACCOUNTS,
	POST_UPDATE_ACCOUNT,
	POST_DELETE_ACCOUNT,
	GET_ENVIRONMENTS,
	POST_ENVIRONMENTS,
	POST_ADD_ENVIRONMENT,
	POST_ADD_ENVIRONMENTS,
	POST_UPDATE_ENVIRONMENT,
	POST_DELETE_ENVIRONMENT,
	OTHER
}
